# Generated by Django 5.0.2 on 2024-03-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookdetail',
            fields=[
                ('student_name', models.CharField(max_length=20)),
                ('reg_no', models.IntegerField()),
                ('dep', models.CharField(max_length=30)),
                ('book_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=30)),
                ('book_refno', models.IntegerField()),
                ('dateof_taken', models.DateField()),
                ('dateof_return', models.DateField()),
            ],
        ),
    ]
